name = "GrowthTop"
uuid = "62be7a3e-eb6e-4285-9b10-c716bac42db9"
authors = ["Aminofa70 <amin.alibakhshi@upm.es> and contributors"]
version = "1.0.0-DEV"

[deps]
Ferrite = "c061ca5d-56c9-439f-9c0e-210fe06d3992"
PUPM = "98242e13-4771-4396-83d3-ad6bca37f0e8"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Ferrite = "1.1.0"
PUPM = "1.0.0"
Statistics = "1.11.1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[sources]
PUPM = {url = "https://github.com/Aminofa70/PUPM.jl"}