name: Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'

      - name: Cache Julia packages
        uses: actions/cache@v4
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-julia-artifacts-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}

      - name: Add PUPM.jl
        run: |
          julia --project=docs -e '
            import Pkg;
            Pkg.add(url="https://github.com/Aminofa70/PUPM.jl");
          '
      
      - name: Install other dependencies
        run: |
          julia --project=docs -e '
            using Pkg;
            # Use local GrowthTop code
            Pkg.develop(path=".");

            # Install all remaining dependencies
            Pkg.instantiate();
          '

      - name: Build and deploy docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=docs docs/make.jl