name: Documentation

on:
  push:
    branches:
      - main  # Change this if your default branch is not "main"
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed to push to gh-pages branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'  # Match your Julia version

      - name: Cache Julia packages
        uses: actions/cache@v4
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-julia-artifacts-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}

      - name: Install dependencies
        run: |
          julia --project=docs -e '
            using Pkg;
            # Use local GrowthTop code
            Pkg.develop(path=".");

            # Use unregistered PUPM package from GitHub
            Pkg.develop(PackageSpec(url="https://github.com/Aminofa70/PUPM.jl"));

            # Install all dependencies
            Pkg.instantiate();
          '

      - name: Build and deploy docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=docs docs/make.jl
